name: hubs
favicon: null
layout_spectrum: 0.8001006133854389
typography_spectrum: 0.13807091605849564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.021311460761353374
  lightness: 0.2766061925794929
  saturation: 0.24592552380636334
  rhythmicContrast: 0.6023389846086502
purpose: []
